/****************************************************************************************/
/*																						*/
/*	© EchoFX, Inc. 2002-2006															*/
/*	All Rights Reserved.																*/
/*																						*/
/****************************************************************************************/

#include "NTZRelease.h"

resource 'aete' (0, "English") {
        0x1,
        0x0,
        english,
        roman,
        {       /* array Suites: 5 elements */
                /* [1] */
                "Required Suite",
                "Terms that every application should support",
                'reqd',
                1,
                1,
                {       /* array Events: 0 elements */
                },
                {       /* array Classes: 0 elements */
                },
                {       /* array ComparisonOps: 0 elements */
                },
                {       /* array Enumerations: 0 elements */
                },
                /* [2] */
                "Standard Suite",
                "Common terms for most applications",
                'CoRe',
                1,
                1,
                {       /* array Events: 10 elements */
                        /* [1] */
                        "close",
                        "Close an object",
                        'core',
                        'clos',
                        noReply,
                        "",
                        replyOptional,
                        singleItem,
                        notEnumerated,
                        notTightBindingFunction,
                        enumsAreConstants,
                        enumListCanRepeat,
                        replyIsValue,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        verbEvent,
                        reserved,
                        reserved,
                        reserved,
                        noParams,
                        "the objects to close",
                        directParamRequired,
                        singleItem,
                        notEnumerated,
                        changesState,
                        enumsAreConstants,
                        enumListCanRepeat,
                        directParamIsValue,
                        directParamIsTarget,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        {       /* array OtherParams: 2 elements */
                                /* [1] */
                                "saving",
                                'savo',
                                'savo',
                                "specifies whether or not changes should be saved before closing",
                                optional,
                                singleItem,
                                enumerated,
                                reserved,
                                enumsAreConstants,
                                enumListCanRepeat,
                                paramIsValue,
                                notParamIsTarget,
                                reserved,
                                reserved,
                                reserved,
                                reserved,
                                prepositionParam,
                                notFeminine,
                                notMasculine,
                                singular,
                                /* [2] */
                                "in",
                                'kfil',
                                'alis',
                                "the file in which to save the object",
                                optional,
                                singleItem,
                                notEnumerated,
                                reserved,
                                enumsAreConstants,
                                enumListCanRepeat,
                                paramIsValue,
                                notParamIsTarget,
                                reserved,
                                reserved,
                                reserved,
                                reserved,
                                prepositionParam,
                                notFeminine,
                                notMasculine,
                                singular
                        },
                        /* [2] */
                        "count",
                        "Return the number of elements of a particular class within an object",
                        'core',
                        'cnte',
                        noReply,
                        "the number of elements",
                        replyRequired,
                        singleItem,
                        notEnumerated,
                        notTightBindingFunction,
                        enumsAreConstants,
                        enumListCanRepeat,
                        replyIsValue,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        verbEvent,
                        reserved,
                        reserved,
                        reserved,
                        noParams,
                        "the object whose elements are to be counted",
                        directParamRequired,
                        singleItem,
                        notEnumerated,
                        doesntChangeState,
                        enumsAreConstants,
                        enumListCanRepeat,
                        directParamIsValue,
                        directParamIsTarget,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        {       /* array OtherParams: 1 elements */
                                /* [1] */
                                "each",
                                'kocl',
                                'type',
                                "the class of the elements to be counted",
                                required,
                                singleItem,
                                notEnumerated,
                                reserved,
                                enumsAreConstants,
                                enumListCanRepeat,
                                paramIsValue,
                                notParamIsTarget,
                                reserved,
                                reserved,
                                reserved,
                                reserved,
                                prepositionParam,
                                notFeminine,
                                notMasculine,
                                singular
                        },
                        /* [3] */
                        "data size",
                        "Return the size in bytes of an object",
                        'core',
                        'dsiz',
                        noReply,
                        "the size of the object in bytes",
                        replyRequired,
                        singleItem,
                        notEnumerated,
                        notTightBindingFunction,
                        enumsAreConstants,
                        enumListCanRepeat,
                        replyIsValue,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        verbEvent,
                        reserved,
                        reserved,
                        reserved,
                        noParams,
                        "the object whose data size is to be returned",
                        directParamRequired,
                        singleItem,
                        notEnumerated,
                        doesntChangeState,
                        enumsAreConstants,
                        enumListCanRepeat,
                        directParamIsValue,
                        directParamIsTarget,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        {       /* array OtherParams: 0 elements */
                        },
                        /* [4] */
                        "exists",
                        "Verify if an object exists",
                        'core',
                        'doex',
                        noReply,
                        "true if it exists, false if not",
                        replyRequired,
                        singleItem,
                        notEnumerated,
                        notTightBindingFunction,
                        enumsAreConstants,
                        enumListCanRepeat,
                        replyIsValue,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        verbEvent,
                        reserved,
                        reserved,
                        reserved,
                        noParams,
                        "",
                        directParamRequired,
                        singleItem,
                        notEnumerated,
                        doesntChangeState,
                        enumsAreConstants,
                        enumListCanRepeat,
                        directParamIsValue,
                        directParamIsTarget,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        {       /* array OtherParams: 0 elements */
                        },
                        /* [5] */
                        "get",
                        "Get the data for an object",
                        'core',
                        'getd',
                        noReply,
                        "The data from the object",
                        replyRequired,
                        singleItem,
                        notEnumerated,
                        notTightBindingFunction,
                        enumsAreConstants,
                        enumListCanRepeat,
                        replyIsValue,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        verbEvent,
                        reserved,
                        reserved,
                        reserved,
                        noParams,
                        "the object whose data is to be returned",
                        directParamRequired,
                        singleItem,
                        notEnumerated,
                        doesntChangeState,
                        enumsAreConstants,
                        enumListCanRepeat,
                        directParamIsValue,
                        directParamIsTarget,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        {       /* array OtherParams: 0 elements */
                        },
                        /* [6] */
                        "make",
                        "Make a new element",
                        'core',
                        'crel',
                        noReply,
                        "Object specifier for the new element",
                        replyRequired,
                        singleItem,
                        notEnumerated,
                        notTightBindingFunction,
                        enumsAreConstants,
                        enumListCanRepeat,
                        replyIsValue,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        verbEvent,
                        reserved,
                        reserved,
                        reserved,
                        noParams,
                        "",
                        directParamOptional,
                        singleItem,
                        notEnumerated,
                        changesState,
                        enumsAreConstants,
                        enumListCanRepeat,
                        directParamIsValue,
                        directParamIsTarget,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        {       /* array OtherParams: 4 elements */
                                /* [1] */
                                "new",
                                'kocl',
                                'type',
                                "the class of the new element",
                                required,
                                singleItem,
                                notEnumerated,
                                reserved,
                                enumsAreConstants,
                                enumListCanRepeat,
                                paramIsValue,
                                notParamIsTarget,
                                reserved,
                                reserved,
                                reserved,
                                reserved,
                                prepositionParam,
                                notFeminine,
                                notMasculine,
                                singular,
                                /* [2] */
                                "at",
                                'insh',
                                'insl',
                                "the location at which to insert the element",
                                optional,
                                singleItem,
                                notEnumerated,
                                reserved,
                                enumsAreConstants,
                                enumListCanRepeat,
                                paramIsValue,
                                notParamIsTarget,
                                reserved,
                                reserved,
                                reserved,
                                reserved,
                                prepositionParam,
                                notFeminine,
                                notMasculine,
                                singular,
                                /* [3] */
                                "with data",
                                'data',
                                '****',
                                "the initial data for the element",
                                optional,
                                singleItem,
                                notEnumerated,
                                reserved,
                                enumsAreConstants,
                                enumListCanRepeat,
                                paramIsValue,
                                notParamIsTarget,
                                reserved,
                                reserved,
                                reserved,
                                reserved,
                                prepositionParam,
                                notFeminine,
                                notMasculine,
                                singular,
                                /* [4] */
                                "with properties",
                                'prdt',
                                'reco',
                                "the initial values for the properties of the element",
                                optional,
                                singleItem,
                                notEnumerated,
                                reserved,
                                enumsAreConstants,
                                enumListCanRepeat,
                                paramIsValue,
                                notParamIsTarget,
                                reserved,
                                reserved,
                                reserved,
                                reserved,
                                prepositionParam,
                                notFeminine,
                                notMasculine,
                                singular
                        },
                        /* [7] */
                        "open",
                        "Open the specified object(s)",
                        'aevt',
                        'odoc',
                        noReply,
                        "",
                        replyOptional,
                        singleItem,
                        notEnumerated,
                        notTightBindingFunction,
                        enumsAreConstants,
                        enumListCanRepeat,
                        replyIsValue,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        verbEvent,
                        reserved,
                        reserved,
                        reserved,
                        noParams,
                        "Objects to open. Can be a list of files or an object specifier.",
                        directParamRequired,
                        singleItem,
                        notEnumerated,
                        changesState,
                        enumsAreConstants,
                        enumListCanRepeat,
                        directParamIsValue,
                        directParamIsTarget,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        {       /* array OtherParams: 0 elements */
                        },
                        /* [8] */
                        "print",
                        "Print the specified object(s)",
                        'aevt',
                        'pdoc',
                        noReply,
                        "",
                        replyOptional,
                        singleItem,
                        notEnumerated,
                        notTightBindingFunction,
                        enumsAreConstants,
                        enumListCanRepeat,
                        replyIsValue,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        verbEvent,
                        reserved,
                        reserved,
                        reserved,
                        noParams,
                        "Objects to print. Can be a list of files or an object specifier.",
                        directParamRequired,
                        singleItem,
                        notEnumerated,
                        doesntChangeState,
                        enumsAreConstants,
                        enumListCanRepeat,
                        directParamIsValue,
                        directParamIsTarget,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        {       /* array OtherParams: 0 elements */
                        },
                        /* [9] */
                        "save",
                        "save a set of objects",
                        'core',
                        'save',
                        noReply,
                        "",
                        replyRequired,
                        singleItem,
                        notEnumerated,
                        notTightBindingFunction,
                        enumsAreConstants,
                        enumListCanRepeat,
                        replyIsValue,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        verbEvent,
                        reserved,
                        reserved,
                        reserved,
                        noParams,
                        "Objects to save.",
                        directParamRequired,
                        singleItem,
                        notEnumerated,
                        doesntChangeState,
                        enumsAreConstants,
                        enumListCanRepeat,
                        directParamIsValue,
                        directParamIsTarget,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        {       /* array OtherParams: 2 elements */
                                /* [1] */
                                "in",
                                'kfil',
                                'alis',
                                "the file in which to save the object(s)",
                                optional,
                                singleItem,
                                notEnumerated,
                                reserved,
                                enumsAreConstants,
                                enumListCanRepeat,
                                paramIsValue,
                                notParamIsTarget,
                                reserved,
                                reserved,
                                reserved,
                                reserved,
                                prepositionParam,
                                notFeminine,
                                notMasculine,
                                singular,
                                /* [2] */
                                "as",
                                'fltp',
                                'type',
                                "the file type of the document in which to save the data",
                                optional,
                                singleItem,
                                notEnumerated,
                                reserved,
                                enumsAreConstants,
                                enumListCanRepeat,
                                paramIsValue,
                                notParamIsTarget,
                                reserved,
                                reserved,
                                reserved,
                                reserved,
                                prepositionParam,
                                notFeminine,
                                notMasculine,
                                singular
                        },
                        /* [10] */
                        "set",
                        "Set an object's data",
                        'core',
                        'setd',
                        noReply,
                        "",
                        replyOptional,
                        singleItem,
                        notEnumerated,
                        notTightBindingFunction,
                        enumsAreConstants,
                        enumListCanRepeat,
                        replyIsValue,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        verbEvent,
                        reserved,
                        reserved,
                        reserved,
                        noParams,
                        "the object to change",
                        directParamRequired,
                        singleItem,
                        notEnumerated,
                        changesState,
                        enumsAreConstants,
                        enumListCanRepeat,
                        directParamIsValue,
                        directParamIsTarget,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        {       /* array OtherParams: 1 elements */
                                /* [1] */
                                "to",
                                'data',
                                '****',
                                "the new value",
                                required,
                                singleItem,
                                notEnumerated,
                                reserved,
                                enumsAreConstants,
                                enumListCanRepeat,
                                paramIsValue,
                                notParamIsTarget,
                                reserved,
                                reserved,
                                reserved,
                                reserved,
                                prepositionParam,
                                notFeminine,
                                notMasculine,
                                singular
                        }
                },
                {       /* array Classes: 3 elements */
                        /* [1] */
                        "application",
                        'capp',
                        "An application program",
                        {       /* array Properties: 0 elements */
                        },
                        {       /* array Elements: 2 elements */
                                /* [1] */
                                'cwin',
                                {       /* array KeyForms: 3 elements */
                                        /* [1] */
                                        'indx',
                                        /* [2] */
                                        'name',
                                        /* [3] */
                                        'rele'
                                },
                                /* [2] */
                                'docu',
                                {       /* array KeyForms: 1 elements */
                                        /* [1] */
                                        'name'
                                }
                        },
                        /* [2] */
                        "window",
                        'cwin',
                        "A Window",
                        {       /* array Properties: 12 elements */
                                /* [1] */
                                "bounds",
                                'pbnd',
                                'qdrt',
                                "the boundary rectangle for the window",
                                reserved,
                                singleItem,
                                notEnumerated,
                                readWrite,
                                enumsAreConstants,
                                enumListCanRepeat,
                                propertyIsValue,
                                reserved,
                                reserved,
                                reserved,
                                reserved,
                                reserved,
                                noApostrophe,
                                notFeminine,
                                notMasculine,
                                singular,
                                /* [2] */
                                "closeable",
                                'hclb',
                                'bool',
                                "Does the window have a close box?",
                                reserved,
                                singleItem,
                                notEnumerated,
                                readOnly,
                                enumsAreConstants,
                                enumListCanRepeat,
                                propertyIsValue,
                                reserved,
                                reserved,
                                reserved,
                                reserved,
                                reserved,
                                noApostrophe,
                                notFeminine,
                                notMasculine,
                                singular,
                                /* [3] */
                                "titled",
                                'ptit',
                                'bool',
                                "Does the window have a title bar?",
                                reserved,
                                singleItem,
                                notEnumerated,
                                readOnly,
                                enumsAreConstants,
                                enumListCanRepeat,
                                propertyIsValue,
                                reserved,
                                reserved,
                                reserved,
                                reserved,
                                reserved,
                                noApostrophe,
                                notFeminine,
                                notMasculine,
                                singular,
                                /* [4] */
                                "index",
                                'pidx',
                                'long',
                                "the number of the window",
                                reserved,
                                singleItem,
                                notEnumerated,
                                readWrite,
                                enumsAreConstants,
                                enumListCanRepeat,
                                propertyIsValue,
                                reserved,
                                reserved,
                                reserved,
                                reserved,
                                reserved,
                                noApostrophe,
                                notFeminine,
                                notMasculine,
                                singular,
                                /* [5] */
                                "floating",
                                'isfl',
                                'bool',
                                "Does the window float?",
                                reserved,
                                singleItem,
                                notEnumerated,
                                readOnly,
                                enumsAreConstants,
                                enumListCanRepeat,
                                propertyIsValue,
                                reserved,
                                reserved,
                                reserved,
                                reserved,
                                reserved,
                                noApostrophe,
                                notFeminine,
                                notMasculine,
                                singular,
                                /* [6] */
                                "modal",
                                'pmod',
                                'bool',
                                "Is the window modal?",
                                reserved,
                                singleItem,
                                notEnumerated,
                                readOnly,
                                enumsAreConstants,
                                enumListCanRepeat,
                                propertyIsValue,
                                reserved,
                                reserved,
                                reserved,
                                reserved,
                                reserved,
                                noApostrophe,
                                notFeminine,
                                notMasculine,
                                singular,
                                /* [7] */
                                "resizable",
                                'prsz',
                                'bool',
                                "Is the window resizable?",
                                reserved,
                                singleItem,
                                notEnumerated,
                                readOnly,
                                enumsAreConstants,
                                enumListCanRepeat,
                                propertyIsValue,
                                reserved,
                                reserved,
                                reserved,
                                reserved,
                                reserved,
                                noApostrophe,
                                notFeminine,
                                notMasculine,
                                singular,
                                /* [8] */
                                "zoomable",
                                'iszm',
                                'bool',
                                "Is the window zoomable?",
                                reserved,
                                singleItem,
                                notEnumerated,
                                readOnly,
                                enumsAreConstants,
                                enumListCanRepeat,
                                propertyIsValue,
                                reserved,
                                reserved,
                                reserved,
                                reserved,
                                reserved,
                                noApostrophe,
                                notFeminine,
                                notMasculine,
                                singular,
                                /* [9] */
                                "zoomed",
                                'pzum',
                                'bool',
                                "Is the window zoomed?",
                                reserved,
                                singleItem,
                                notEnumerated,
                                readWrite,
                                enumsAreConstants,
                                enumListCanRepeat,
                                propertyIsValue,
                                reserved,
                                reserved,
                                reserved,
                                reserved,
                                reserved,
                                noApostrophe,
                                notFeminine,
                                notMasculine,
                                singular,
                                /* [10] */
                                "name",
                                'pnam',
                                'itxt',
                                "the title of the window",
                                reserved,
                                singleItem,
                                notEnumerated,
                                readWrite,
                                enumsAreConstants,
                                enumListCanRepeat,
                                propertyIsValue,
                                reserved,
                                reserved,
                                reserved,
                                reserved,
                                reserved,
                                noApostrophe,
                                notFeminine,
                                notMasculine,
                                singular,
                                /* [11] */
                                "visible",
                                'pvis',
                                'bool',
                                "is the window visible?",
                                reserved,
                                singleItem,
                                notEnumerated,
                                readOnly,
                                enumsAreConstants,
                                enumListCanRepeat,
                                propertyIsValue,
                                reserved,
                                reserved,
                                reserved,
                                reserved,
                                reserved,
                                noApostrophe,
                                notFeminine,
                                notMasculine,
                                singular,
                                /* [12] */
                                "position",
                                'ppos',
                                'QDpt',
                                "upper left coordinates of window",
                                reserved,
                                singleItem,
                                notEnumerated,
                                readOnly,
                                enumsAreConstants,
                                enumListCanRepeat,
                                propertyIsValue,
                                reserved,
                                reserved,
                                reserved,
                                reserved,
                                reserved,
                                noApostrophe,
                                notFeminine,
                                notMasculine,
                                singular
                        },
                        {       /* array Elements: 0 elements */
                        },
                        /* [3] */
                        "document",
                        'docu',
                        "A Document",
                        {       /* array Properties: 2 elements */
                                /* [1] */
                                "name",
                                'pnam',
                                'itxt',
                                "the title of the document",
                                reserved,
                                singleItem,
                                notEnumerated,
                                readOnly,
                                enumsAreConstants,
                                enumListCanRepeat,
                                propertyIsValue,
                                reserved,
                                reserved,
                                reserved,
                                reserved,
                                reserved,
                                noApostrophe,
                                notFeminine,
                                notMasculine,
                                singular,
                                /* [2] */
                                "modified",
                                'imod',
                                'bool',
                                "Has the document been modified since the last save?",
                                reserved,
                                singleItem,
                                notEnumerated,
                                readOnly,
                                enumsAreConstants,
                                enumListCanRepeat,
                                propertyIsValue,
                                reserved,
                                reserved,
                                reserved,
                                reserved,
                                reserved,
                                noApostrophe,
                                notFeminine,
                                notMasculine,
                                singular
                        },
                        {       /* array Elements: 0 elements */
                        }
                },
                {       /* array ComparisonOps: 0 elements */
                },
                {       /* array Enumerations: 1 elements */
                        /* [1] */
                        'savo',
                        {       /* array Enumerators: 3 elements */
                                /* [1] */
                                "yes",
                                'yes ',
                                "Save objects now",
                                /* [2] */
                                "no",
                                'no  ',
                                "Do not save objects",
                                /* [3] */
                                "ask",
                                'ask ',
                                "Ask the user whether to save"
                        }
                },
                /* [3] */
                "Miscellaneous Standards",
                "Useful events that aren't in any other suite",
                'misc',
                0,
                0,
                {       /* array Events: 1 elements */
                        /* [1] */
                        "revert",
                        "Revert an object to the most recently saved version",
                        'misc',
                        'rvrt',
                        noReply,
                        "",
                        replyOptional,
                        singleItem,
                        notEnumerated,
                        notTightBindingFunction,
                        enumsAreConstants,
                        enumListCanRepeat,
                        replyIsValue,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        verbEvent,
                        reserved,
                        reserved,
                        reserved,
                        noParams,
                        "object to revert",
                        directParamRequired,
                        singleItem,
                        notEnumerated,
                        doesntChangeState,
                        enumsAreConstants,
                        enumListCanRepeat,
                        directParamIsValue,
                        directParamIsTarget,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        {       /* array OtherParams: 0 elements */
                        }
                },
                {       /* array Classes: 0 elements */
                },
                {       /* array ComparisonOps: 0 elements */
                },
                {       /* array Enumerations: 0 elements */
                },
                /* [4] */
                "odds and ends",
                "Things that should be in some standard suite, but aren't",
                'Odds',
                1,
                1,
                {       /* array Events: 2 elements */
                        /* [1] */
                        "SetTellTarget",
                        "Makes an object the \"focus\" of AppleEvents",
                        'ppnt',
                        'sttg',
                        noReply,
                        "",
                        replyRequired,
                        singleItem,
                        notEnumerated,
                        notTightBindingFunction,
                        enumsAreConstants,
                        enumListCanRepeat,
                        replyIsValue,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        verbEvent,
                        reserved,
                        reserved,
                        reserved,
                        noParams,
                        "",
                        directParamRequired,
                        singleItem,
                        notEnumerated,
                        doesntChangeState,
                        enumsAreConstants,
                        enumListCanRepeat,
                        directParamIsValue,
                        directParamIsTarget,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        {       /* array OtherParams: 1 elements */
                                /* [1] */
                                "to",
                                'data',
                                'obj ',
                                "reference to new focus of AppleEvents",
                                optional,
                                singleItem,
                                notEnumerated,
                                reserved,
                                enumsAreConstants,
                                enumListCanRepeat,
                                paramIsValue,
                                notParamIsTarget,
                                reserved,
                                reserved,
                                reserved,
                                reserved,
                                prepositionParam,
                                notFeminine,
                                notMasculine,
                                singular
                        },
                        /* [2] */
                        "select",
                        "Select the specified object",
                        'misc',
                        'slct',
                        noReply,
                        "",
                        replyOptional,
                        singleItem,
                        notEnumerated,
                        notTightBindingFunction,
                        enumsAreConstants,
                        enumListCanRepeat,
                        replyIsValue,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        verbEvent,
                        reserved,
                        reserved,
                        reserved,
                        noParams,
                        "the object to select",
                        directParamOptional,
                        singleItem,
                        notEnumerated,
                        changesState,
                        enumsAreConstants,
                        enumListCanRepeat,
                        directParamIsValue,
                        directParamIsTarget,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        {       /* array OtherParams: 0 elements */
                        }
                },
                {       /* array Classes: 0 elements */
                },
                {       /* array ComparisonOps: 0 elements */
                },
                {       /* array Enumerations: 0 elements */
                },
                /* [5] */
                "Capture",
                "",
                'efxc',
                1,
                1,
                {       /* array Events: 3 elements */
                        /* [1] */
                        "start recording",
                        "Start recording a movie, e.g.\n"
						"start recording\n"
						"start recording as \"myMovie.mov\", or\n"
						"start recording window \"USBVision\" as \"myMovie.mov\"",
                        'efxc',
                        'Star',
                        noReply,
                        "",
                        replyOptional,
                        singleItem,
                        notEnumerated,
                        notTightBindingFunction,
                        enumsAreConstants,
                        enumListCanRepeat,
                        replyIsValue,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        verbEvent,
                        reserved,
                        reserved,
                        reserved,
                        noParams,
                        "",
                        directParamOptional,
                        singleItem,
                        notEnumerated,
                        doesntChangeState,
                        enumsAreConstants,
                        enumListCanRepeat,
                        directParamIsValue,
                        directParamIsTarget,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        {       /* array OtherParams: 3 elements */
                                /* [1] */
                                "as",
                                'kFil',
                                'fss ',
                                "The filename or path of the file. If no name is given "
								"the user will be prompted for one unless auto-naming is on.",
                                optional,
                                singleItem,
                                notEnumerated,
                                reserved,
                                enumsAreConstants,
                                enumListCanRepeat,
                                paramIsValue,
                                notParamIsTarget,
                                reserved,
                                reserved,
                                reserved,
                                reserved,
                                prepositionParam,
                                notFeminine,
                                notMasculine,
                                singular,
                                /* [2] */
                                "window",
                                'kWch',
                                'TEXT',
                                "The name of the window to record. If no name is given, "
								"then the front window is assumed.",
                                optional,
                                singleItem,
                                notEnumerated,
                                reserved,
                                enumsAreConstants,
                                enumListCanRepeat,
                                paramIsValue,
                                notParamIsTarget,
                                reserved,
                                reserved,
                                reserved,
                                reserved,
                                prepositionParam,
                                notFeminine,
                                notMasculine,
                                singular,
                                /* [3] */
                                "duration",
                                'kDur',
                                'magn',
                                "Desired duration of the recording in seconds.",
                                optional,
                                singleItem,
                                notEnumerated,
                                reserved,
                                enumsAreConstants,
                                enumListCanRepeat,
                                paramIsValue,
                                notParamIsTarget,
                                reserved,
                                reserved,
                                reserved,
                                reserved,
                                prepositionParam,
                                notFeminine,
                                notMasculine,
                                singular
                        },
                        /* [2] */
                        "stop recording",
                        "Stops recording a movie, e.g.\n"
						"stop recording, or\n"
						"stop recording window \"USBVision\"",
                        'efxc',
                        'Stop',
                        noReply,
                        "",
                        replyOptional,
                        singleItem,
                        notEnumerated,
                        notTightBindingFunction,
                        enumsAreConstants,
                        enumListCanRepeat,
                        replyIsValue,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        verbEvent,
                        reserved,
                        reserved,
                        reserved,
                        noParams,
                        "",
                        directParamOptional,
                        singleItem,
                        notEnumerated,
                        doesntChangeState,
                        enumsAreConstants,
                        enumListCanRepeat,
                        directParamIsValue,
                        directParamIsTarget,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        {       /* array OtherParams: 1 elements */
                                /* [1] */
                                "window",
                                'kWch',
                                'TEXT',
                                "The name of the window to stop recording from. If no "
								"name is given, then the front window is assumed.",
                                optional,
                                singleItem,
                                notEnumerated,
                                reserved,
                                enumsAreConstants,
                                enumListCanRepeat,
                                paramIsValue,
                                notParamIsTarget,
                                reserved,
                                reserved,
                                reserved,
                                reserved,
                                prepositionParam,
                                notFeminine,
                                notMasculine,
                                singular
                        },
                        /* [3] */
                        "take snapshot",
                        "Takes a snapshot, e.g.\n"
						"take snapshot\n"
						"take snaphot as \"snapshot\", or\n"
						"take snapshot window \"USBVision\" as \"snapshot\"\n"
						"The parameter \"large\" can be added for digitizer specific functionality.\n"
						"The format of the picture is set by \"Snapshot Settings…\"",
                        'efxc',
                        'Snap',
                        noReply,
                        "",
                        replyOptional,
                        singleItem,
                        notEnumerated,
                        notTightBindingFunction,
                        enumsAreConstants,
                        enumListCanRepeat,
                        replyIsValue,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        verbEvent,
                        reserved,
                        reserved,
                        reserved,
                        noParams,
                        "",
                        directParamOptional,
                        singleItem,
                        notEnumerated,
                        doesntChangeState,
                        enumsAreConstants,
                        enumListCanRepeat,
                        directParamIsValue,
                        directParamIsTarget,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        reserved,
                        {       /* array OtherParams: 3 elements */
                                /* [1] */
                                "as",
                                'kFil',
                                'fss ',
                                "The filename or path of the file. If no name is given "
								"the user will be prompted for one unless auto-naming is on.",
                                optional,
                                singleItem,
                                notEnumerated,
                                reserved,
                                enumsAreConstants,
                                enumListCanRepeat,
                                paramIsValue,
                                notParamIsTarget,
                                reserved,
                                reserved,
                                reserved,
                                reserved,
                                prepositionParam,
                                notFeminine,
                                notMasculine,
                                singular,
                                /* [2] */
                                "window",
                                'kWch',
                                'TEXT',
                                "The name of the window to snapshot. If no name is given, "
								"then the front window is assumed.",
                                optional,
                                singleItem,
                                notEnumerated,
                                reserved,
                                enumsAreConstants,
                                enumListCanRepeat,
                                paramIsValue,
                                notParamIsTarget,
                                reserved,
                                reserved,
                                reserved,
                                reserved,
                                prepositionParam,
                                notFeminine,
                                notMasculine,
                                singular,
                                /* [3] */
                                "large",
                                'kLrg',
                                'bool',
                                "The size of the snapshot desired. If not specified, the "
								"current frame size is used. If \"large\" is specified "
								"and the digitizer supports it, a digitizer specific "
                                "larger picture will be produced.",
                                optional,
                                singleItem,
                                notEnumerated,
                                reserved,
                                enumsAreConstants,
                                enumListCanRepeat,
                                paramIsValue,
                                notParamIsTarget,
                                reserved,
                                reserved,
                                reserved,
                                reserved,
                                prepositionParam,
                                notFeminine,
                                notMasculine,
                                singular
                        }
                },
                {       /* array Classes: 0 elements */
                },
                {       /* array ComparisonOps: 0 elements */
                },
                {       /* array Enumerations: 0 elements */
                }
        }
};

resource 'aedt' (16000) {
        {       /* array: 3 elements */
                /* [1] */
                1701214307, 1400136050, 16000,
                /* [2] */
                1701214307, 1400139632, 16001,
                /* [3] */
                1701214307, 1399742832, 16002
        }
};
